### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by KevCH24** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-KevCH24#1]
[LIBRERIAS EN C# KEVIN CRUZ HERNANDEZ.pdf](https://github.com/SistemasTecTlaxiaco/Infografia-Kevin-Cruz-Hernandez/files/14539747/LIBRERIAS.EN.C.KEVIN.CRUZ.HERNANDEZ.pdf)

**Comment by Kim-Mendoza3** [comment]
Calificacion 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
